name: Bump version and tag main

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  bumptag:
    runs-on: ubuntu-latest
    outputs:
      GITTAGVER: ${{ steps.set_version.outputs.GITTAGVER }}
    steps:
      - id: checkout
        name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - id: set_version
        name: Set tag version and apply tag
        run: |
          tmpversion="$(./scripts/bump_tag_main_latest.sh)"
          echo "Bumpted to tag $tmpversion"
